### ISSUE TITLE
setting up and running

### ISSUE THREAD

**Issue by qsabyasachi** [vieiraeduardos/quiz#2]
I would like to create collections and other data structures in mongo. These queries are not in the repository.

I also am facing issues in running the run.py file showing error 
File "C:\Users\userme\Downloads\quiz-master\quiz\quiz\__init__.py", line 15, in <module>
    from quiz.controllers.quiz import routes, CourseController, QuestionController, TopicController, UserController, TestController, AnswerController, ClassController
ImportError: No module named controllers.quiz

**Comment by vieiraeduardos** [comment]
@qsabyasachi unfortunately this project was discontinued by me. I should warn all.

**Comment by vieiraeduardos** [comment]
I tested on my computer now. It is working. Do you import all necessary libraries?

Do it:
1. Download the current version of the project.
git clone https://github.com/vieiraeduardos/quiz.git

2. Import all libraries with the command:
pip install -r requirements.txt

3. Execute
python run.py
